# Generated by Django 5.1.15 on 2026-09-06 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('connection_type', models.CharField(choices=[('bluetooth', 'Bluetooth'), ('wifi', 'Wi-Fi / Network'), ('usb', 'USB')], default='bluetooth', max_length=20)),
                ('address', models.CharField(blank=True, help_text='IP address or Bluetooth MAC', max_length=200)),
                ('paper_size', models.CharField(choices=[('58mm', '58mm'), ('80mm', '80mm')], default='80mm', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='shop.shop')),
            ],
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('receipt', 'Receipt'), ('kitchen_slip', 'Kitchen Slip'), ('test', 'Test Print')], max_length=20)),
                ('token_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('printing', 'Printing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_msg', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='printer.printer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
