# Generated by Django 6.0.6 on 2026-06-15 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gstin', models.CharField(blank=True, max_length=20, verbose_name='GSTIN')),
                ('fssai', models.CharField(blank=True, max_length=20, verbose_name='FSSAI Number')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop/logos/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='shop/qr_codes/')),
                ('payment_modes_config', models.CharField(default='Both', max_length=20)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('table_count', models.PositiveIntegerField(default=0)),
                ('upi_id', models.CharField(blank=True, max_length=100, verbose_name='UPI ID')),
                ('bill_settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shop',
            },
        ),
        migrations.CreateModel(
            name='BillTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.ImageField(blank=True, null=True, upload_to='bill_templates/logos/')),
                ('shop_name', models.CharField(blank=True, max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('qr_code_url', models.ImageField(blank=True, null=True, upload_to='bill_templates/qr_codes/')),
                ('show_invoice_number', models.BooleanField(default=True)),
                ('show_date_time', models.BooleanField(default=True)),
                ('show_customer_details', models.BooleanField(default=True)),
                ('show_discount', models.BooleanField(default=True)),
                ('show_tax', models.BooleanField(default=True)),
                ('show_item_name', models.BooleanField(default=True)),
                ('show_quantity', models.BooleanField(default=True)),
                ('show_unit_price', models.BooleanField(default=True)),
                ('show_total_price', models.BooleanField(default=True)),
                ('show_subtotal', models.BooleanField(default=True)),
                ('show_round_off', models.BooleanField(default=True)),
                ('show_grand_total', models.BooleanField(default=True)),
                ('show_payment_method', models.BooleanField(default=True)),
                ('show_upi_id', models.BooleanField(default=True)),
                ('footer_message', models.TextField(blank=True, default='Thank you for visiting!')),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('theme_color', models.CharField(blank=True, default='#000000', max_length=50)),
                ('template_design', models.CharField(blank=True, default='standard', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill_template', to='shop.shop')),
            ],
            options={
                'verbose_name': 'Bill Template',
            },
        ),
    ]
