# Generated by Django 6.0.6 on 2026-07-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='sms_credits',
            field=models.PositiveIntegerField(default=100, verbose_name='SMS Credits'),
        ),
    ]
