# Generated by Django 6.0.6 on 2026-10-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
