# Generated by Django 5.1.15 on 2026-09-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='items_summary',
            field=models.TextField(blank=True, help_text='Summary of items for easy viewing in DB'),
        ),
    ]
