# Generated by Django 5.1.15 on 2026-10-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('pending_verification', 'Pending OTP Verification'), ('pending', 'Pending Approval'), ('trial', 'Trial Period'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Trial Expired')], default='pending', max_length=20),
        ),
    ]
