# Generated by Django 6.0.6 on 2026-07-07 06:41

from django.db import migrations


def approve_existing_users(apps, schema_editor):
    User = apps.get_model('core', 'User')
    User.objects.all().update(account_status='approved')

def reverse_approve(apps, schema_editor):
    User = apps.get_model('core', 'User')
    User.objects.all().update(account_status='pending')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_account_status_user_approved_at_and_more'),
    ]

    operations = [
        migrations.RunPython(approve_existing_users, reverse_approve),
    ]
