# Generated by Django 6.0.6 on 2026-07-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20260707_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
