# Generated by Django 6.0.6 on 2026-07-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_systemsettings_subscriptionpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='payment_qr_code',
            field=models.TextField(blank=True, help_text='Base64 encoded QR code image stored directly in DB for persistence on cloud servers', null=True),
        ),
    ]
