# Generated by Django 6.0.6 on 2026-08-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_qr_code_to_base64_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='bill_body_font_size_mm',
            field=models.FloatField(default=6.0, help_text='Global printable bill body text font height in mm'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='bill_footer_font_size_mm',
            field=models.FloatField(default=5.0, help_text='Global printable bill footer font height in mm'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='bill_grand_total_font_size_mm',
            field=models.FloatField(default=10.0, help_text='Global printable bill grand total font height in mm'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='bill_subtotal_font_size_mm',
            field=models.FloatField(default=7.0, help_text='Global printable bill subtotal font height in mm'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='bill_title_font_size_mm',
            field=models.FloatField(default=20.0, help_text='Global printable bill title/shop name font height in mm'),
        ),
    ]
